<div class="main">
    <h1>Password Reset</h1>
    <em class="alt">Submit your password reset request.</em>
    <p>&nbsp;</p>
    <p>Please provide your email address which has to match with the registered email address in order to receive the password reset instruction.</p>
    <input type="text" name="email" />
    <button class="green-button reset" type="submit" name="submit" value="submit">
        <span>submit</span>
    </button>
</div>
<div class="CTA">
    <button class="grey-button first close" data-role="test">close</button>
</div>

