<div class="main">
    <h1>User Registration</h1>
    <em class="alt error">All fields are required</em>
    <p class="overlay error"></p>
    <table id="user">
        <tr>
            <td>Username</td>
            <td><input type="text" name="username" /></td>
        </tr>
        <tr>
            <td>Password</td>
            <td><input type="text" name="password" /></td>
        </tr>
        <tr>
            <td>Email</td>
            <td><input type="text" name="email" /></td>
        </tr>
        <tr>
            <td>First Name</td>
            <td><input type="text" name="first_name" /></td>
        </tr>
        <tr>
            <td>Last Name</td>
            <td><input type="text" name="last_name" /></td>
        </tr>
        <tr>
            <td>User Type</td>
            <td>
                <select name="user_type">
                    <option value="1">admin</option>
                    <option value="2" selected>student</option>
                    <option value="3">faculty</option>
                </select>
            </td>
        </tr>
    </table>
</div>
<div class="CTA">
    <button class="green-button submit first" id="new-user"><span>submit</span></button>
    <button class="black-button close"><span>cancel</span></button>

</div>