<div class="main">
    <h1>User Information</h1>
    <em class="alt error">All fields are required</em>
    <p class="overlay error"></p>
    <span class="button remove" data="<?php echo $this->user['id']; ?>">remove</span>
    <table id="user">
        <tr>
            <td>Username</td>
            <td><input type="text" name="username" value="<?php echo $this->user['username']; ?>" /></td>
        </tr>
        <tr>
            <td>Email</td>
            <td><input type="text" name="email" value="<?php echo $this->user['email']; ?>" /></td>
        </tr>
        <tr>
            <td>First Name</td>
            <td><input type="text" name="first_name" value="<?php echo $this->user['first_name']; ?>" /></td>
        </tr>
        <tr>
            <td>Last Name</td>
            <td><input type="text" name="last_name" value="<?php echo $this->user['last_name']; ?>" /></td>
        </tr>
        <tr>
            <td>User Type</td>
            <td>
                <select name="user_type">
                    <option value="1" <?php echo $this->user['user_type'] == '1' ? 'selected' : ''; ?>>admin</option>
                    <option value="2" <?php echo $this->user['user_type'] == '2' ? 'selected' : ''; ?>>student</option>
                    <option value="3" <?php echo $this->user['user_type'] == '3' ? 'selected' : ''; ?>>faculty</option>
                </select>
            </td>
        </tr>
    </table>
</div>
<div class="CTA">
    <button class="green-button first" id="user-update" data="<?php echo $this->user['id']; ?>"><span>update</span></button>
    <button class="black-button close"><span>cancel</span></button>

</div>