<table id="course-table">
    <tr>
        <td width="80"><b>Date</b></td>
        <td width="80"><b>Student ID</b></td>
        <td width="100"><b>Payment Type</b></td>
        <td width="60"><b>Amount</b></td>
        <td><b>Reason</b></td>
        <?php if ($this->admin) { ?>
        <td width="150"><b>Option</b></td>
        <?php } ?>
    </tr>

    <?php if (count($this->payments) > 0) { ?>
        <?php foreach ($this->payments as $row) { ?>

            <tr id="<?php echo $row['id']; ?>">
                <td><?php echo $row['date']; ?></td>
                <td><?php echo $row['student_id']; ?></td>
                <td><?php echo $row['type_str']; ?></td>
                <td><?php echo $row['type'] != '1' ? '- ' : ''; ?>$<?php echo $row['amount']; ?></td>
                <td><?php echo $row['reason']['reason']; ?></td>
                <?php if ($this->admin) { ?>
                <td>
                    <span class="button-light edit" id="<?php echo $row['id']; ?>_edit_button">edit</span>
                    <span class="button-light delete" id="<?php echo $row['id']; ?>_delete_button">delete</span>
                </td>
                <?php } ?>
            </tr>
            <?php if ($this->admin) { ?>
            <tr id="<?php echo $row['id']; ?>_edit" class="hide">
                <td><input class="date" type="text" id="<?php echo $row['id']; ?>_date" value="<?php echo $row['date']; ?>"/></td>
                <td><?php echo $row['student_id']; ?></td>
                <td>
                    <select class="payment_type" id="<?php echo $row['id']; ?>_type">
                        <?php echo $row['typeOptions']; ?>
                    </select>
                </td>
                <td><input class="amount" type="text" id="<?php echo $row['id']; ?>_amount" value="<?php echo $row['amount']; ?>"/></td>
                <td>
                    <select class="payment_reason" id="<?php echo $row['id']; ?>_reason">
                        <?php echo $row['reasonOptions']; ?>
                    </select>
                </td>
                <td>
                    <span class="button-light save" id="<?php echo $row['id']; ?>_save">save</span>
                    <span class="button-light cancel" id="<?php echo $row['id']; ?>_cancel">cancel</span>
                </td>
            </tr>
            <?php } ?>

        <?php } ?>
        <tr>
            <td colspan="6">Current account balance: $<?php echo $this->balance; ?></td>
        </tr>
    <?php
        } else {
    ?>
        <tr>
            <td colspan="6" align="center"><b>No Payment History Exists...</b></td>
        </tr>
    <?php } ?>
    <?php if ($this->admin) { ?>
    <tr id="new_line">
        <td colspan="6" align="center">
            <a class="overlay-link" data="payment-new" bind="true">Create new payment record</a>
        </td>
    </tr>
    <?php } ?>
</table>
