<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <?php echo $this->headTitle('Disciples v1.0'); ?>
    <link href="/disciples/css/layout-mobile.css" media="screen" rel="stylesheet" type="text/css" />
    <link rel="icon" type="image/png" href="/disciples/images/icons/favicon.png">
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <script type="text/javascript" src="/disciples/js/jquery.min.js"></script>
    <script type="text/javascript" src="/disciples/js/interaction.js"></script>
    <?php echo $this->headScript(); ?>
    <script src="http://www.google.com/jsapi"></script>
    <script>
        google.load( "webfont", "1" );
        google.setOnLoadCallback(function() {
            WebFont.load({ custom: {
                families: [ "NanumGothic" ],
                urls: [ "http://fontface.kr/NanumGothic/css" ]
            }});
        });
    </script>
</head>
<body>
	<div id="wrapper">
		<div id="content">
            <div id="content-panel">
                <?php
                echo $this->partial('_header-mobile.phtml', array(
                    'hideUserInfo' => $this->hideUserInfo,
                    'user' => $this->user
                ));

                echo $this->layout()->content;

                echo $this->partial('_footer.phtml', array('user' => $this->user));
                ?>
            </div>
		</div>
    </div>
</body>
</html>