<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle('Disciples v1.0'); ?>    
    <link href="/css/layout.css" media="screen" rel="stylesheet" type="text/css" />
    <link rel="icon" type="image/png" href="/images/icons/favicon.png">
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script type="text/javascript" src="/js/interaction.js"></script>
    <?php echo $this->headScript(); ?>
    <script src="http://www.google.com/jsapi"></script>
    <script>
        google.load( "webfont", "1" );
        google.setOnLoadCallback(function() {
            WebFont.load({ custom: {
                families: [ "NanumGothic" ],
                urls: [ "http://fontface.kr/NanumGothic/css" ]
            }});
        });
    </script>
</head>
<body>
	<div id="wrapper">
		<div id="content">
            <?php
                echo $this->partial('_header.phtml', array(
                    'hideUserInfo' => $this->hideUserInfo,
                    'user' => $this->user
                ));
            ?>
            <div id="content-panel">
                <?php echo $this->layout()->content; ?>
            </div>
		</div>
        <?php echo $this->partial('_footer.phtml', array('user' => $this->user)); ?>
    </div>
</body>
</html>