<?php
    $this->headScript()->appendFile('/js/index.js');
?>
<div class="inner-right">
    <h1>
        SIGN IN<br>
        <em class="alt<?php echo $this->loggedout ? ' error' : ''; ?>">
        <?php echo $this->loggedout ? 'You have been signed out. Sign in again below.' : 'Welcome to NWPTS Member System'; ?>
        </em>
    </h1>
    
    <?php echo $this->errorMessage; ?>

    <form name="login" method="POST" action="">
        <fieldset>
            <dl class="<?php echo $this->formError['username'] ? 'invalid' : ''; ?>">
                <dt>
                    <input id="login" type="text" name="username" value="<?php echo $this->username; ?>" />
                    <label class="pseudo-label">Username</label>
                    <span class="validation-arrow">&nbsp;</span>
                </dt>
                <dd>
                    <span class="validation">Please Enter a valid Username</span>
                </dd>
            </dl>
            <dl class="<?php echo $this->formError['password'] ? 'invalid' : ''; ?>">
                <dt>
                    <input id="password" type="password" name="password" value="" />
                    <label class="pseudo-label">Password</label>
                    <span class="validation-arrow">&nbsp;</span>
                </dt>
                <dd>
                    <span class="validation">Please Enter a valid Password</span>
                </dd>
            </dl>
        </fieldset>
        <button class="green-button" type="submit" name="submit" value="login">
            <span>login</span>
        </button>
    </form>
    </br>
    <p>
        <a class="overlay-link" data="password-reset">Forgot your password?</a>
    </p>

    <a href="/index/register">New student sign up here.</a>
</div>