<div class="back-button-container" xmlns="http://www.w3.org/1999/html">

</div>
<div class="inner-right">
    <h1>Admin Operations<br /><em class="alt">Managing the admin data</em></h1>
    <p><h5>Please select one of the options you'd like to perform...</h5></p>

    <a href="/admin/user"><span class="button wide">Managing User Data</span></a>
    <a href="/admin/student"><span class="button wide">Managing Student Data</span></a><br />
    <a href="/admin/faculty"><span class="button wide">Managing Faculty Data</span></a>
    <a href="/admin/course"><span class="button wide">Managing Course Data</span></a><br />
    <a href="/admin/student-course"><span class="button wide">Managing Student-Course Data</span></a>
    <a href="/admin/payment"><span class="button wide">Managing Payment Data</span></a>

</div>